apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt-newt-main-tunnel
  namespace: newt
spec:
  template:
    spec:
      containers:
        - name: newt
          args:
            - --blueprint-file=/etc/pangolin/blueprint.yaml
