global:
  networkPolicy:
    create: true
    defaultDenyIngress: true

metrics:
  enabled: true
  port: 2112

newtInstances:
  - name: main-tunnel
    auth:
      existingSecretName: newt-credentials
    acceptClients: true
