global:
  networkPolicy:
    create: true
    defaultDenyIngress: true

metrics:
  enabled: true
  port: 2112

newtInstances:
  - name: main-tunnel
    enabled: true
    auth:
      existingSecretName: newt-credentials
    acceptClients: true
    extraVolumes:
      - name: blueprint
        configMap:
          name: pangolin-blueprint
    extraVolumeMounts:
      - name: blueprint
        mountPath: /etc/pangolin
        readOnly: true
