apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - recurringjob.yaml
  - http-route.yaml

helmCharts:
  - name: longhorn
    namespace: longhorn-system
    releaseName: longhorn
    repo: https://charts.longhorn.io
    valuesFile: values.yaml
    version: 1.10.1
