apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ./chart
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: cert-manager
  namespace: cert-manager
  version: 0.0.0
