apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cert-canmugrons.yaml
  - cert-cornfakes.yaml
  - gw-external.yaml
  - gw-internal.yaml
  - gw-tls-passthrough.yaml
