apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omada

resources:
  - ../../base
  - statefulset.yaml
  - svc.yaml
  - svc-lb.yaml
  - tls-route.yaml
  - cert-omada.yaml

generatorOptions:
  disableNameSuffixHash: true
