apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ./chart
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: kube-prometheus-stack
  namespace: monitoring
  version: 0.0.0
