apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - selinux-intelgpudevice-cm.yaml
  - selinux-intelgpudevice-ds.yaml

helmCharts:
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts/
    version: 0.26.0
    releaseName: dp-operator
    includeCRDs: true
    namespace: inteldeviceplugins-system
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts/
    version: 0.26.0
    releaseName: intel-gpu
    includeCRDs: true
    namespace: inteldeviceplugins-system
    valuesInline:
      nodeFeatureRule: true
