apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kured
  repo: https://kubereboot.github.io/charts
  version: 5.10.0
  releaseName: kured
  namespace: kube-system
  valuesFile: values.yaml
  includeCRDs: true
