apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- http-route.yaml

helmCharts:
  - name: argocd
    repo: https://argoproj.github.io/argo-helm
    version: 9.1.0
    releaseName: argo-cd
    namespace: argocd
    valuesFile: values.yaml
